version: '3.8'

services:
  # PHP (Laravel)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./conf/nginx-site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # Composer (اختياري - تقدر تستخدمه لتثبيت الحزم)
  composer:
    image: composer:2
    container_name: laravel-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: ["composer", "install", "--no-dev", "--optimize-autoloader"]

volumes:
  mysql_data:
